### ISSUE TITLE
有道云笔记，有三种签到方式，可不可以全部实现自动签到呢？

### ISSUE THREAD

**Issue by BigBigBIgMan** [BlueHtml/Note163Checkin#16]
有道云笔记，可以电脑客户端，手机客户端，网页三种方式签单，看着现在只是实现了网页签到，手机、电脑端是还需要手动签到，大神是否考虑将这两端也实现了呢？

**Comment by BlueHtml** [comment]
@BigBigBIgMan 你说的 手机、电脑端的签到，能贴下图并且标记一下在哪里吗？我想了解下咱们俩说的签到是否是同一个？
另外我这里在运行程序后，再在**电脑端**点击签到，会提示`出错，您今天已签到过`

**Comment by BigBigBIgMan** [comment]
> @BigBigBIgMan
我用的是windows 和 安卓设备，有道笔记版本是最新版本，是可以点击签到的；且签到时领取的空间，与自动领取的数量是不一样。

**Comment by BigBigBIgMan** [comment]
> @BigBigBIgMan 你说的 手机、电脑端的签到，能贴下图并且标记一下在哪里吗？我想了解下咱们俩说的签到是否是同一个？ 另外我这里在运行程序后，再在**电脑端**点击签到，会提示`出错，您今天已签到过`

我用的是windows 和 安卓设备，有道笔记版本是最新版本，是可以点击签到的；且签到时领取的空间，与自动领取的数量是不一样。
