### ISSUE TITLE
脚本好像失效了

### ISSUE THREAD

**Issue by zhoudahong** [BlueHtml/Note163Checkin#2]
总是提示”登录失败，请检查账号密码是否正确！或者在网页上登录后再次运行本程序！”。
好像脚本失效了，报上面的错，能烦请再更新一下脚本吗，谢谢了！

**Comment by BlueHtml** [comment]
> 总是提示”登录失败，请检查账号密码是否正确！或者在网页上登录后再次运行本程序！”。 好像脚本失效了，报上面的错，能烦请再更新一下脚本吗，谢谢了！

加了前置校验，不太好弄，周末我看看能不能搞。如果不行的话只能填cookie了

**Comment by zylbiubiubiu** [comment]
> > 总是提示”登录失败，请检查账号密码是否正确！或者在网页上登录后再次运行本程序！”。 好像脚本失效了，报上面的错，能烦请再更新一下脚本吗，谢谢了！
> 
> 加了前置校验，不太好弄，周末我看看能不能搞。如果不行的话只能填cookie了

原来如此，整了半天没整明白，等大佬整。

**Comment by BlueHtml** [comment]
已更新：
1. 添加redis配置，用来存储cookie。后续可以重用这个cookie，避免频繁登录账号。这个配置是**可选**的，个人建议配置一下，可以使用[redislabs](https://app.redislabs.com/)的免费套餐。
2. **取消**了自动运行，需要自行在`.github/workflows/main.yml`添加定时任务。
