### ISSUE TITLE
登录失效后，如何手动抓cookie

### ISSUE THREAD

**Issue by jinde98** [BlueHtml/Note163Checkin#20]
![image](https://github.com/BlueHtml/Note163Checkin/assets/127750182/fe6c1734-cbd8-4050-8c65-89b9570d3686)
 图中这一堆，哪个是啊，还是一个个都要复制下来？

**Comment by BlueHtml** [comment]
@jinde98 随便打开个网页，cookie的值全部复制下来，如下图：

![image](https://github.com/BlueHtml/Note163Checkin/assets/17940898/2a7999da-8f7a-405b-83db-2f3774446508)

**Comment by jinde98** [comment]
我用这个地址https://note.youdao.com/mobileSignIn/login_mobile.html?&back_url=https://note.youdao.com/web/&from=web 登陆可以跳过验证，但是python的selenium只能抓取到的cookie比在浏览器中network下的cookie少两个YNOTE_SESS 和 __yadk_uid Cookie这两组数据。  具体如下：

gdxidpyhxdE=3M%5CiSWw3OmjG%2B3B7TbG***RddXpR86Xqva67vhvYEMZRcRr9cwJBy9jVUPGflEzD6YN2CcTRXrWuCjg8bQjaQjq%5CAy%5CBBy4TjaIMk2mG30pjq9Jen**ASys%5CsDnjLeP6IdJP4wxEJVI%5Cyq5djOPA%2B7%5C2%2FWf7z%5Cs6wMrvZxS%2FBcbT6ML%3A1706061380900; YNOTE_LOGIN=1||1706060487292; __yadk_uid=u3VvhFh**BmmoC8cHfr5z75M; YNOTE_CSTK=Il-vPf8f

大佬有没办法通过这个地址自动抓取完整的cookie

**Comment by BlueHtml** [comment]
@jinde98 谢谢你发的登录地址，项目已更新，现在可以自动登录了，请同步最新代码

![image](https://github.com/BlueHtml/Note163Checkin/assets/17940898/a66c0cef-60d1-41e8-ae14-6a06731b18f7)
